//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

package Presentation;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class ImportProductGUI {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JTextField pathtextbox;
    private JButton jcomp4;
    private JFrame frame;

    public ImportProductGUI() {
        //construct components
        frame = new JFrame("Import");
        jcomp1 = new JLabel ("Import products");
        jcomp2 = new JLabel ("Select path:");
        pathtextbox = new JTextField (5);
        jcomp4 = new JButton ("Import");

        //adjust size and set layout
        frame.setSize(361, 189);
        frame.setLayout(null);
        frame.setVisible (true);

        //add components
        frame.add(jcomp1);
        frame.add(jcomp2);
        frame.add(pathtextbox);
        frame.add(jcomp4);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (135, 40, 100, 25);
        jcomp2.setBounds (10, 100, 100, 25);
        pathtextbox.setBounds (90, 100, 255, 25);
        jcomp4.setBounds (125, 145, 100, 25);
    }
    public void addImportProductListener2(ActionListener a) {
        jcomp4.addActionListener(a);
    }
    public String getPath() {
        return pathtextbox.getText();
    }
    public void closeView() {
        frame.setVisible(false);
    }
    public static void main (String[] args) {
       ImportProductGUI p = new ImportProductGUI();
    }
}
